### ISSUE TITLE
Windows GUI용 executable 지원

### ISSUE THREAD

**Issue by haksungjang** [sktelecom/onot#6]
Python 환경 구축이 곤란한 사용자를 위한 Windows GUI용 executable 지원이 필요합니다. 
- PyQt5로 input file을 선택하고 오픈소스 고지문을 생성하기 위한 간단한 GUI를 구성하고, 
- PyInstaller로 executable을 생성

**Comment by HyunMinH** [comment]
@haksungjang 
안녕하세요~ 카카오 로저스입니다:)

이 이슈를 진행하기 위해 PyQt5 로 환경셋팅을 하려고 했는데요.
제가 개발용으로 사용하고 있는 M1 맥북에서는 해당버전으로 설치가 안되는 이슈가 있습니다.

다행히 최신버전인 PyQt6는 M1에서 정상적으로 동작하고 윈도우에서도 샘플로 만든 exe 파일도 잘 동작합니다.
PyQt5와 PyQt6의 차이점들은 대부분 마이너하다고 하여 별 문제는 없어보이는데 PyQt6로 진행해도 괜찮을까요?
https://coderslegacy.com/differences-between-pyqt5-and-pyqt6/

**Comment by haksungjang** [comment]
안녕하세요, 로저스!

아, 그렇군요! PyQt6로 진행하셔도 문제 되지 않습니다. Python CLI에 익숙하지 않은 윈도우 사용자를 위한 GUI 제공이 가능하다면 PyQt가 아닌 다른 GUI 도구를 사용해도 좋습니다. 

감사합니다. :)

**Comment by HyunMinH** [comment]
그럼 PyQt6로 진행하겠습니다.
감사합니다^^

**Comment by haksungjang** [comment]
@HyunMinH 님, 

PR 감사합니다! Merge하였습니다. :) 
덕분에 큰 기능이 잘 정리되었습니다. 

감사합니다.
